# Generated by Django 3.1.12 on 2024-12-05 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='mechanic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='next_service_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='warranty_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_serviced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold'), ('Scrapped', 'Scrapped')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Truck', 'Truck'), ('Bike', 'Bike')], default='Car', max_length=10),
        ),
    ]
