# Generated by Django 3.1.12 on 2024-12-05 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20241205_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True),
        ),
    ]
